name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login In To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-gateway -f ./apps/gateway/Dockerfile --target production .
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-notification -f ./apps/notification/Dockerfile --target production .
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-order -f ./apps/order/Dockerfile --target production .
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-payment -f ./apps/payment/Dockerfile --target production .
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-product -f ./apps/product/Dockerfile --target production .
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-user -f ./apps/user/Dockerfile --target production .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-notification
          docker push ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-order
          docker push ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-payment
          docker push ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-product
          docker push ${{ secrets.DOCKER_USERNAME }}/fc-nestjs-user
